# Generated by Django 2.2.9 on 2019-12-30 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='summary',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
