# Generated by Django 2.2.9 on 2020-01-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20191230_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
