# Generated by Django 2.2.9 on 2020-01-01 17:07

from django.db import migrations, models
import django.db.models.deletion
import survey_app_repo.survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20200101_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=400)),
                ('question_type', models.CharField(choices=[(survey_app_repo.survey.models.QuestionTypes('Description'), 'Description'), (survey_app_repo.survey.models.QuestionTypes('Text'), 'Text')], max_length=4)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.Survey')),
            ],
        ),
    ]
