# Generated by Django 2.2.9 on 2020-01-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20200102_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Description', 'DESC'), ('Text', 'TEXT')], max_length=255),
        ),
    ]
