# Generated by Django 2.2.9 on 2020-01-05 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_surveyresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(blank=True, max_length=400, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question')),
                ('survey_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyResponse')),
            ],
            options={
                'unique_together': {('question', 'survey_response')},
            },
        ),
    ]
