# Generated by Django 2.2.9 on 2020-01-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_responsetext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
